remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-8ZC36LC0HH
show_downloads: true
github:
  zip_url: https://github.com/steinhaug/UARPC/archive/refs/tags/v1.6.4.zip
